"""
OpenMem CLI Tool
Memory System for AI-powered Development
"""

import os
import sys
import argparse
import yaml
from datetime import datetime

from openmem import MemoryManager
from openmem.features.trigger import SmartTrigger


def cmd_init(args):
    """Initialize Memory"""
    if args.global_init:
        memory_dir = os.path.expanduser("~/.memory")
    else:
        memory_dir = os.path.join(os.getcwd(), ".memory")
    
    if os.path.exists(memory_dir) and not args.force:
        print(f"Warning: Memory already exists: {memory_dir}")
        print(f"   Use --force to reinitialize")
        return
    
    os.makedirs(memory_dir, exist_ok=True)
    
    project_name = args.project_name or os.path.basename(os.getcwd())
    template = args.template or "minimal"
    
    if not args.yes:
        print(f"\nOpenMem Initialization")
        print(f"   Directory: {memory_dir}")
        print(f"   Project: {project_name}")
        print(f"   Template: {template}")
        print()
        
        confirm = input("Confirm? [Y/n]: ").strip().lower()
        if confirm and confirm != 'y':
            print("Cancelled")
            return
    
    config = _generate_config(project_name, template, args.global_init)
    
    config_path = os.path.join(memory_dir, "config.yaml")
    with open(config_path, 'w', encoding='utf-8') as f:
        yaml.dump(config, f, allow_unicode=True, default_flow_style=False)
    
    os.makedirs(os.path.join(memory_dir, "rules"), exist_ok=True)
    os.makedirs(os.path.join(memory_dir, "sessions"), exist_ok=True)
    os.makedirs(os.path.join(memory_dir, "knowledge"), exist_ok=True)
    os.makedirs(os.path.join(memory_dir, "backups"), exist_ok=True)
    
    if template != "minimal":
        rules_path = os.path.join(memory_dir, "rules", "project.md")
        rules_content = _generate_rules(project_name, template, args.ide)
        with open(rules_path, 'w', encoding='utf-8') as f:
            f.write(rules_content)
    
    print(f"\nInitialized: {memory_dir}")
    print(f"   Config: {config_path}")
    
    if template != "minimal":
        print(f"   Rules: {rules_path}")


def _generate_config(project_name: str, template: str, is_global: bool) -> dict:
    """Generate config"""
    config = {
        'version': '0.1.1',
    }
    
    if not is_global:
        config['project'] = {
            'name': project_name,
            'path': os.getcwd(),
        }
    
    if template == "minimal":
        config['memory_types'] = {
            'decision': {'enabled': True},
            'milestone': {'enabled': True},
        }
    elif template == "standard":
        config['memory_types'] = {
            'decision': {'enabled': True, 'sync_to_global': False},
            'milestone': {'enabled': True, 'sync_to_global': False},
            'issue': {'enabled': True},
            'knowledge': {'enabled': True, 'sync_to_global': True},
        }
    else:  # full
        config['memory_types'] = {
            'decision': {'enabled': True, 'sync_to_global': True},
            'milestone': {'enabled': True, 'sync_to_global': True},
            'issue': {'enabled': True},
            'knowledge': {'enabled': True, 'sync_to_global': True},
            'session': {'enabled': True},
            'archive': {'enabled': True},
        }
    
    config['storage'] = {
        'type': 'sqlite',
        'path': 'memory.db',
        'wal_mode': True,
        'busy_timeout': 30000,
        'enable_fts': True,
    }
    
    config['search'] = {
        'highlight': True,
        'tokenizer': 'jieba',
    }
    
    if template in ("standard", "full"):
        config['backup'] = {
            'auto': True,
            'max_backups': 7,
        }
    
    return config


def _generate_rules(project_name: str, template: str, ide: str = "both") -> str:
    """Generate rules file (supports Trae and VS Code)"""

    content = f"""# {project_name} Project Rules

> Auto-generated by Memory System

## Project Info

- Project Name: {project_name}
- Created: {datetime.now().strftime('%Y-%m-%d')}
- Template: {template}
- IDE: {ide}

"""

    if template == "standard":
        content += """## Memory Types

| Type | Description |
|:---|:---|
| decision | Important technical decisions |
| milestone | Project milestones |
| issue | Issue records |
| knowledge | Knowledge documents |

"""
    elif template == "full":
        content += """## Memory Types

| Type | Description | Sync to Global |
|:---|:---|:---|
| decision | Important technical decisions | Optional |
| milestone | Project milestones | Optional |
| issue | Issue records | No |
| knowledge | Knowledge documents | Yes |
| session | Session records | No |
| archive | Archived content | No |

"""

    # Trae Skill format
    if ide in ("trae", "both"):
        content += """
---
## Trae IDE Config

Memory file location: `.memory/rules/project.md`

### Memory Type Description

- **decision**: Important technical decisions (e.g., tech stack, architecture)
- **milestone**: Project milestones (e.g., feature completion, releases)
- **issue**: Issue records (e.g., bugs, solutions)
- **knowledge**: Knowledge documents (e.g., learning notes)

"""

    # VS Code format
    if ide in ("vscode", "both"):
        content += """
---
## VS Code Config

### Project Docs

Memory file location: `.memory/rules/project.md`

### Usage

1. Manage project memories in `.memory/` directory
2. Use `omem add` to add memories
3. Use `omem search` to search memories

### Memory Types

- decision: Important technical decisions
- milestone: Project milestones
- issue: Issue records
- knowledge: Knowledge documents

"""

    return content


def cmd_status(args):
    """Show status"""
    memory_dir = os.path.expanduser("~/.memory")
    project_dir = os.path.join(os.getcwd(), ".memory")

    print("📊 Memory Status\n")

    if os.path.exists(memory_dir):
        print(f"✅ Global Memory: {memory_dir}")
        db_path = os.path.join(memory_dir, "memory.db")
        config_path = os.path.join(memory_dir, "config.yaml")
        
        if os.path.exists(db_path):
            size = os.path.getsize(db_path)
            print(f"   Database: {size / 1024:.1f} KB")

        if os.path.exists(config_path):
            with open(config_path, 'r', encoding='utf-8') as f:
                cfg = yaml.safe_load(f)
                version = cfg.get('version', 'unknown')
                print(f"   Version: {version}")

        if args.verbose:
            memory = MemoryManager()
            count = memory.count(scope="global")
            print(f"   Memories: {count}")
            memory.close()
    else:
        print(f"⚠️  Global Memory not initialized")

    print()

    if os.path.exists(project_dir):
        print(f"✅ Project Memory: {project_dir}")
        db_path = os.path.join(project_dir, "memory.db")

        if os.path.exists(db_path):
            size = os.path.getsize(db_path)
            print(f"   Database: {size / 1024:.1f} KB")

        if args.verbose:
            memory = MemoryManager(project_path=os.getcwd())
            count = memory.count(scope="project")
            print(f"   Memories: {count}")
            memory.close()
    else:
        print(f"⚠️  Project Memory not initialized")
        print(f"   Run 'omem init' to initialize")


def cmd_add(args):
    """Add memory"""
    project_path = args.project if args.project else os.getcwd()
    memory = MemoryManager(project_path=project_path)
    
    content = args.content
    memory_type = args.type
    
    # Auto-detect type (if not specified)
    if not memory_type or memory_type == "auto":
        trigger = SmartTrigger()
        result = trigger.analyze(content)
        if result.triggered:
            memory_type = result.trigger_type.value
            print(f"🔍 Auto-detected type: {memory_type} (confidence: {result.confidence:.2f})")
            if result.keywords:
                print(f"   Keywords: {', '.join(result.keywords)}")
        else:
            memory_type = "decision"
            print(f"🔍 No trigger type detected, defaulting to decision")

    memory_id = memory.add(
        content=content,
        type=memory_type,
        tags=args.tags.split(',') if args.tags else None,
        priority=args.priority,
        scope=args.scope
    )

    print(f"✅ Memory added: ID={memory_id}")
    memory.close()


def cmd_record(args):
    """Record conversation to raw"""
    from openmem.features.organizer import Organizer

    organizer = Organizer()
    session_id = organizer.add_message(role=args.role, content=args.content)
    print(f"✅ Recorded to raw: {session_id}")


def cmd_search(args):
    """Search memories"""
    project_path = args.project if args.project else os.getcwd()
    memory = MemoryManager(project_path=project_path)

    results = memory.search(
        query=args.query,
        limit=args.limit,
        scope=args.scope
    )

    if not results:
        print("No matching memories found")
        memory.close()
        return

    print(f"Found {len(results)} results:\n")
    for r in results:
        print(f"  [{r['id']}] {r['type']}")
        print(f"  {r['content'][:80]}...")
        if r.get('tags'):
            print(f"  Tags: {', '.join(r['tags'])}")
        print()

    memory.close()


def cmd_list(args):
    """List memories"""
    project_path = args.project if args.project else os.getcwd()
    memory = MemoryManager(project_path=project_path)

    results = memory.list(
        type=args.type,
        limit=args.limit,
        scope=args.scope
    )

    if not results:
        print("No memories yet")
        memory.close()
        return

    print(f"Total {len(results)} memories:\n")
    for r in results:
        print(f"  [{r['id']}] {r['type']} | {r['created_at'][:19]}")
        print(f"  {r['content'][:60]}...")
        print()

    memory.close()


def cmd_page(args):
    """Paginate memories"""
    project_path = args.project if args.project else os.getcwd()
    memory = MemoryManager(project_path=project_path)

    result = memory.page(
        page=args.page,
        page_size=args.page_size,
        memory_type=args.type,
        scope=args.scope
    )

    print(f"Page {result['page'] + 1}/{result['total_pages']}")
    print(f"Total {result['total']} items\n")

    for r in result['messages']:
        print(f"  [{r['id']}] {r['content'][:50]}...")

    memory.close()


def cmd_organize(args):
    """Organize meeting minutes"""
    from openmem.features.organizer import Organizer, format_conversation, build_prompt, format_summary_md, parse_summary
    from openmem.features.llm import get_llm_client

    organizer = Organizer()

    if args.session:
        messages = organizer.get_raw_messages(session_id=args.session)
    elif args.date:
        messages = organizer.get_raw_messages(date=args.date)
    else:
        messages = organizer.get_recent_raw(days=args.days)

    if not messages:
        print("No raw records found")
        return

    print(f"📝 Total {len(messages)} raw messages")

    conversation = format_conversation(messages)
    prompt = build_prompt(conversation)

    if args.auto:
        print("\n🤖 Auto AI organization in progress...")
        try:
            llm = get_llm_client(provider=args.llm)
            response = llm.chat(prompt)

            summary = parse_summary(response)
            summary.raw_count = len(messages)

            filepath = organizer.save_summary(summary)
            print(f"\n✅ Summary saved: {filepath}")
            print("\n📄 Preview:")
            print(format_summary_md(summary))
        except Exception as e:
            print(f"\n❌ Call failed: {e}")
            print("Check config or use --llm to specify another model")
        return

    print("\n" + "=" * 50)
    print("📋 Organize Prompt:")
    print("=" * 50)
    print(prompt)
    print("=" * 50)
    print("\n💡 Use --auto to auto-organize with AI")


def cmd_raw(args):
    """View raw records"""
    from openmem.features.organizer import Organizer

    organizer = Organizer()
    date = args.date if args.date else datetime.now().strftime("%Y-%m-%d")
    messages = organizer.get_raw_messages(date=date)

    if not messages:
        print(f"No records found for {date}")
        return

    print(f"📝 {date} Raw records (total {len(messages)})\n")
    for i, msg in enumerate(messages[:args.limit]):
        role = "👤 User" if msg.role == "user" else "🤖 AI"
        print(f"{i+1}. {role}")
        print(f"   {msg.content[:100]}{'...' if len(msg.content) > 100 else ''}\n")


def cmd_summary(args):
    """View summaries"""
    from openmem.features.organizer import Organizer

    organizer = Organizer()
    date = args.date if args.date else datetime.now().strftime("%Y-%m-%d")
    filepath = os.path.join(organizer.summaries_dir, f"{date}.md")

    if not os.path.exists(filepath):
        print(f"No summary found for {date}")
        return

    with open(filepath, encoding="utf-8") as f:
        content = f.read()

    print(f"📋 {date} Meeting Summary\n")
    print(content)


def main():
    """Main entry point"""
    parser = argparse.ArgumentParser(
        prog='openmem',
        description='OpenMem - Memory System for AI-powered Development',
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    
    subparsers = parser.add_subparsers(dest='command', help='Available commands')
    
    # init
    parser_init = subparsers.add_parser('init', help='Initialize Memory')
    parser_init.add_argument('--global', dest='global_init', action='store_true',
                           help='Initialize global Memory (~/.memory)')
    parser_init.add_argument('--template', choices=['minimal', 'standard', 'full'],
                           help='Select template')
    parser_init.add_argument('--ide', choices=['trae', 'vscode', 'both'], default='both',
                           help='Target IDE (default: both)')
    parser_init.add_argument('--project-name', help='Project name')
    parser_init.add_argument('--yes', '-y', action='store_true',
                           help='Non-interactive mode')
    parser_init.add_argument('--force', '-f', action='store_true',
                           help='Force reinitialize')
    
    # status
    parser_status = subparsers.add_parser('status', help='Show status')
    parser_status.add_argument('--verbose', '-v', action='store_true',
                              help='Show detailed information')
    
    # add
    parser_add = subparsers.add_parser('add', help='Add memory')
    parser_add.add_argument('content', help='Memory content')
    parser_add.add_argument('--type', default='auto', help='Memory type (auto/decision/milestone/issue/knowledge)')
    parser_add.add_argument('--tags', help='Tags (comma-separated)')
    parser_add.add_argument('--priority', type=int, default=0, help='Priority')
    parser_add.add_argument('--scope', default='project', choices=['project', 'global'],
                          help='Scope')
    parser_add.add_argument('--project', help='Project path')
    
    # record
    parser_record = subparsers.add_parser('record', help='Record conversation to raw')
    parser_record.add_argument('--role', default='user', choices=['user', 'assistant'], help='Role')
    parser_record.add_argument('content', help='Conversation content')
    
    # search
    parser_search = subparsers.add_parser('search', help='Search memories')
    parser_search.add_argument('query', help='Search keyword')
    parser_search.add_argument('--limit', type=int, default=10, help='Result count')
    parser_search.add_argument('--scope', default='project', 
                            choices=['project', 'global', 'both'],
                            help='Scope')
    parser_search.add_argument('--project', help='Project path')
    
    # list
    parser_list = subparsers.add_parser('list', help='List memories')
    parser_list.add_argument('--type', help='Memory type')
    parser_list.add_argument('--limit', type=int, default=20, help='Result count')
    parser_list.add_argument('--scope', default='project',
                            choices=['project', 'global'],
                            help='Scope')
    parser_list.add_argument('--project', help='Project path')
    
    # page
    parser_page = subparsers.add_parser('page', help='Paginate memories')
    parser_page.add_argument('--page', type=int, default=0, help='Page number')
    parser_page.add_argument('--page-size', type=int, default=20, help='Page size')
    parser_page.add_argument('--type', help='Memory type')
    parser_page.add_argument('--scope', default='project',
                           choices=['project', 'global'],
                           help='Scope')
    parser_page.add_argument('--project', help='Project path')
    
    # organize
    parser_org = subparsers.add_parser('organize', help='Organize meeting notes')
    parser_org.add_argument('--date', help='Date (YYYY-MM-DD, default today)')
    parser_org.add_argument('--days', type=int, default=1, help='Recent N days')
    parser_org.add_argument('--session', help='Session ID')
    parser_org.add_argument('--dry-run', action='store_true', help='Preview only, do not save')
    parser_org.add_argument('--auto', action='store_true', help='Auto organize with AI')
    parser_org.add_argument('--llm', default='ollama', choices=['ollama', 'deepseek', 'openai'],
                        help='LLM provider (default: ollama)')
    
    # raw
    parser_raw = subparsers.add_parser('raw', help='View raw records')
    parser_raw.add_argument('--date', help='Date (YYYY-MM-DD, default today)')
    parser_raw.add_argument('--limit', type=int, default=50, help='Display count')
    
    # summary
    parser_summary = subparsers.add_parser('summary', help='View summary')
    parser_summary.add_argument('--date', help='Date (YYYY-MM-DD, default today)')
    
    args = parser.parse_args()
    
    if not args.command:
        parser.print_help()
        return
    
    commands = {
        'init': cmd_init,
        'status': cmd_status,
        'add': cmd_add,
        'record': cmd_record,
        'search': cmd_search,
        'list': cmd_list,
        'page': cmd_page,
        'organize': cmd_organize,
        'raw': cmd_raw,
        'summary': cmd_summary,
    }
    
    commands[args.command](args)


if __name__ == '__main__':
    main()
